library:
  source-dirs: src
tests:
  chapter7-test:
    source-dirs: test
    main: Spec.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter7
copyright: 2020 Author name here
maintainer: example@example.com
dependencies:
- either
- base >= 4.7 && < 5
- lens >= 4.18.0
- containers
- text
- transformers
name: chapter7
version: 0.1.0.0
extra-source-files:
- README.md
- ChangeLog.md
author: Author name here
github: githubuser/chapter7
license: BSD3
executables:
  chapter7-exe:
    source-dirs: app
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter7
description: Please see the README on GitHub at <https://github.com/githubuser/chapter7#readme>
